### ISSUE TITLE
Logops v2 tracking issue

### ISSUE THREAD

**Issue by jmendiara** [telefonicaid/logops#37]
As #36 discussion says, we are going to start working in the v2 release to address Breaking changes from node v6 that we have inherited

- [x] Make master node < 6 compatible. Bump 1.0.8  [#38]
- [x] Create `release/1.X` branch and 1.0.8 tag
- [x] Set master to be v2 code, only with node > 6 compatible code [#39]
- [x] Release 1.0.8
- [x] Set deprecation notice in npm v < 1.0.7
- [x] Bump and Release 2.0.0
